
-- PEDIDOS 

-- ID PEDIDO 
-- ID PRODUCTO 
-- CANTIDAD DE UNIDADES 
-- CLEITNE 
-- FEHCA SOLICITUDAD 
-- FECHA PRODUCTO LISTO
-- COSTO DEL PEDIDO (PRECIO X CNAITDA)
-- ABONADO SI/NO

-- PRODUCTOS 

-- 1) NOMBRE
-- 2) CODIGO 
-- 3) PRECIO VENTA MINORISTA
-- 4) PRECIO VENCTA MAYORISTA 
-- 5) CANTIDAD MAYORISTA
-- 6) DIAS DE PRODUCCION 
-- 7) ID CATEGORIA

-- TABLA CATEGORIA 

-- 1) ID 
-- 2) NOMBRE CATEGORIA 

-- CLIENTES 

-- 1) APELLIO ==> NOT NULL  
-- 2) NOMBRE ==> NOT NULL 
-- 3) FECHA DE NACIMIETO 
-- 4) MAIL 
-- 5) TELEFONO LINEA 
-- 6) CELULAR 
-- 7) REGISTRO WEB 

-- COLABORADORES

-- 1) LEGAJO (NUMERICO)
-- 2) APELLIDO 
-- 3) NOMBRE 
-- 4) FEHCA DE NACIMIETO 
-- 5) AÑO DE INGRESO A LA FABRICA ===> MAYO A 1990
-- 6) SULDO ACTUAL 
-- 7) MODALIDAD DE TRABAJO ("F" FULLTIME - "P" PARTTIME)
USE MASTER 
GO 

CREATE DATABASE Actividad1_3
GO

USE Actividad1_3
GO 

CREATE TABLE Pedido(
    ID BIGINT PRIMARY KEY NOT NULL,
    IDProducto INT NOT NULL,        -- FK (PRODUCTO)
    Cantidad SMALLINT NOT NULL, 
    IDCliente INT NOT NULL,         -- FK (CLIETE) 
    FechaPedido DATE NOT NULL, 
    FechaProductoListo DATE NULL,
    TotalPedido MONEY NOT NULL, 
    Abonado BIT NOT NULL
)

GO 
CREATE TABLE Categoria(
    ID INT PRIMARY KEY,
    NombreCate VARCHAR (100) NOT NULL
)

GO
CREATE TABLE Producto(
    ID INT PRIMARY KEY NOT NULL,
    IDCategoria INT NOT NULL FOREIGN KEY REFERENCES Categoria (ID),
    Nombre VARCHAR (100) NOT NULL,
    PrecioMinorista MONEY NOT NULL,
    PrecioMayorista MONEY NOT NULL,
    CantMayorista SMALLINT NOT NULL,
    DiasProd SMALLINT NOT NULL,
    
)

GO
CREATE TABLE Cliente(
    ID INT PRIMARY KEY NOT NULL,
    Apellido VARCHAR (50) NOT NULL,
    Nombre VARCHAR (50) NOT NULL,
    FNacimieto DATE NULL,
    Mail VARCHAR (200) NULL,
    TelFijo VARCHAR (15) NULL,
    Celular VARCHAR (15) NULL,
    RegWeb BIT NOT NULL
)

GO
CREATE TABLE Colaborador(
    Legajo INT NOT NULL PRIMARY KEY,
    Apellido VARCHAR (50) NOT NULL,
    Nombre VARCHAR (50) NOT NULL,
    FNacimieto DATE NOT NULL,
    FIngreso SMALLINT NOT NULL CHECK (FIngreso > 1990),
    Sueldo MONEY NOT NULL,
    ModTrabajo CHAR NOT NULL CHECK (ModTrabajo in ('F', 'P'))
)

GO
ALTER TABLE Pedido
ADD CONSTRAINT FK_Pedido_Producto FOREIGN KEY (IDProducto)
REFERENCES Producto (ID)

GO
ALTER TABLE Pedido
ADD CONSTRAINT FK_Pedido_Cliente FOREIGN KEY (IDCliente)
REFERENCES Cliente (ID)



